export const SUPABASE_URL = 'https://app.tech4ag.my';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzYzMzczNjQ1LCJleHAiOjIwNzg3MzM2NDV9.vZOedqJzUn01PjwfaQp7VvRzSm4aRMr21QblPDK8AoY';
export const ADMIN_PWD = "ppdag@12345";

export const groupConfig = {
    "G1": { label: "MATEMATIK (SR)", subjects: ["MATEMATIK (SR)"], d1: "20 Julai 2026", d2: "21 Julai 2026", exemptS1: 1, exemptS2: 2 },
    "G2": { label: "SAINS (SR)", subjects: ["SAINS (SR)"], d1: "22 Julai 2026", d2: "23 Julai 2026", exemptS1: 3, exemptS2: 4 },
    "G3": { label: "MATEMATIK & SAINS KOMPUTER (SM)", subjects: ["MATEMATIK (SM)", "SAINS KOMPUTER (SM)"], d1: "10 Ogos 2026", d2: "11 Ogos 2026", exemptS1: 5, exemptS2: 6 },
    "G4": { label: "SAINS & SAINS TULEN (SM)", subjects: ["SAINS (SM)", "SAINS TULEN (SM)"], d1: "12 Ogos 2026", d2: "13 Ogos 2026", exemptS1: 7, exemptS2: 8 }
};

export const subjectDatesMap = {
    "MATEMATIK (SR)": { s1: "2026-07-20", s2: "2026-07-21" },
    "SAINS (SR)": { s1: "2026-07-22", s2: "2026-07-23" },
    "MATEMATIK (SM)": { s1: "2026-08-10", s2: "2026-08-11" },
    "SAINS KOMPUTER (SM)": { s1: "2026-08-10", s2: "2026-08-11" },
    "SAINS (SM)": { s1: "2026-08-12", s2: "2026-08-13" },
    "SAINS TULEN (SM)": { s1: "2026-08-12", s2: "2026-08-13" }
};

export const absoluteDates = [
    "2026-07-20", "2026-07-21", "2026-07-22", "2026-07-23",
    "2026-08-10", "2026-08-11", "2026-08-12", "2026-08-13"
];

export const WORKSHOP_LAT = 2.3448043344238445;
export const WORKSHOP_LNG = 102.1049791621177;
export const MAX_RADIUS_METERS = 200;

export const masterSekolah = [
    { kod: "MBA0001", nama: "SEKOLAH KEBANGSAAN MASJID TANAH", jenis: "SK" },
    { kod: "MBA0002", nama: "SEKOLAH KEBANGSAAN TANJUNG BIDARA", jenis: "SK" },
    { kod: "MBA0003", nama: "SEKOLAH KEBANGSAAN OTHMAN SYAWAL", jenis: "SK" },
    { kod: "MBA0004", nama: "SEKOLAH KEBANGSAAN BUKIT BERINGIN", jenis: "SK" },
    { kod: "MBA0005", nama: "SEKOLAH KEBANGSAAN RAMUAN CHINA BESAR", jenis: "SK" },
    { kod: "MBA0006", nama: "SEKOLAH KEBANGSAAN RAMUAN CHINA KECHIL", jenis: "SK" },
    { kod: "MBA0007", nama: "SEKOLAH KEBANGSAAN AYER LIMAU", jenis: "SK" },
    { kod: "MBA0008", nama: "SEKOLAH KEBANGSAAN KUALA LINGGI", jenis: "SK" },
    { kod: "MBA0009", nama: "SEKOLAH KEBANGSAAN PENGKALAN BALAK", jenis: "SK" },
    { kod: "MBA0010", nama: "SEKOLAH KEBANGSAAN DURIAN DAUN (K)", jenis: "SK" },
    { kod: "MBA0011", nama: "SEKOLAH KEBANGSAAN LUBOK REDAN", jenis: "SK" },
    { kod: "MBA0012", nama: "SEKOLAH KEBANGSAAN JERAM", jenis: "SK" },
    { kod: "MBA0013", nama: "SEKOLAH KEBANGSAAN AIR JERNIH", jenis: "SK" },
    { kod: "MBA0014", nama: "SEKOLAH KEBANGSAAN KAMPUNG TENGAH", jenis: "SK" },
    { kod: "MBA0015", nama: "SEKOLAH KEBANGSAAN SUNGAI TUANG", jenis: "SK" },
    { kod: "MBA0016", nama: "SEKOLAH KEBANGSAAN TELOK BEREMBANG", jenis: "SK" },
    { kod: "MBA0017", nama: "SEKOLAH KEBANGSAAN SUNGAI JERNIH", jenis: "SK" },
    { kod: "MBA0018", nama: "SEKOLAH KEBANGSAAN RANTAU PANJANG", jenis: "SK" },
    { kod: "MBA0020", nama: "SEKOLAH KEBANGSAAN PADANG SEBANG", jenis: "SK" },
    { kod: "MBA0021", nama: "SEKOLAH KEBANGSAAN AYER PA'ABAS", jenis: "SK" },
    { kod: "MBA0022", nama: "SEKOLAH KEBANGSAAN SIMPANG EMPAT", jenis: "SK" },
    { kod: "MBA0023", nama: "SEKOLAH KEBANGSAAN PULAU SEBANG", jenis: "SK" },
    { kod: "MBA0024", nama: "SEKOLAH KEBANGSAAN MELEKEK", jenis: "SK" },
    { kod: "MBA0025", nama: "SEKOLAH KEBANGSAAN GANUN", jenis: "SK" },
    { kod: "MBA0026", nama: "SEKOLAH KEBANGSAAN PARIT MELANA", jenis: "SK" },
    { kod: "MBA0027", nama: "SEKOLAH KEBANGSAAN SUNGAI PETAI", jenis: "SK" },
    { kod: "MBA0028", nama: "SEKOLAH KEBANGSAAN SUNGAI SIPUT", jenis: "SK" },
    { kod: "MBA0029", nama: "SEKOLAH KEBANGSAAN MELAKA PINDAH", jenis: "SK" },
    { kod: "MBA0030", nama: "SEKOLAH KEBANGSAAN PEGOH", jenis: "SK" },
    { kod: "MBA0031", nama: "SEKOLAH KEBANGSAAN BERISU", jenis: "SK" },
    { kod: "MBA0032", nama: "SEKOLAH KEBANGSAAN LENDU", jenis: "SK" },
    { kod: "MBA0033", nama: "SEKOLAH KEBANGSAAN BELIMBING DALAM", jenis: "SK" },
    { kod: "MBA0034", nama: "SEKOLAH KEBANGSAAN RUMBIA", jenis: "SK" },
    { kod: "MBA0035", nama: "SEKOLAH KEBANGSAAN SUNGAI BULOH", jenis: "SK" },
    { kod: "MBA0036", nama: "SEKOLAH KEBANGSAAN CHERANA PUTEH", jenis: "SK" },
    { kod: "MBA0037", nama: "SEKOLAH KEBANGSAAN TEBONG", jenis: "SK" },
    { kod: "MBA0038", nama: "SEKOLAH KEBANGSAAN KEMUNING", jenis: "SK" },
    { kod: "MBA0039", nama: "SEKOLAH KEBANGSAAN MENGGONG", jenis: "SK" },
    { kod: "MBA0040", nama: "SEKOLAH KEBANGSAAN HUTAN PERCHA", jenis: "SK" },
    { kod: "MBA0041", nama: "SEKOLAH KEBANGSAAN DURIAN TUNGGAL", jenis: "SK" },
    { kod: "MBA0042", nama: "SEKOLAH KEBANGSAAN KEM TERENDAK II", jenis: "SK" },
    { kod: "MBA0043", nama: "SEKOLAH KEBANGSAAN GANGSA", jenis: "SK" },
    { kod: "MBA0044", nama: "SEKOLAH KEBANGSAAN LESONG BATU", jenis: "SK" },
    { kod: "MBA0045", nama: "SEKOLAH KEBANGSAAN DEMANG TAHA", jenis: "SK" },
    { kod: "MBB0041", nama: "SEKOLAH KEBANGSAAN ALOR GAJAH 1", jenis: "SK" },
    { kod: "MBB0042", nama: "SEKOLAH KEBANGSAAN DATO' NANING", jenis: "SK" },
    { kod: "MBB0043", nama: "SEKOLAH KEBANGSAAN DATUK TAMBICHIK KARIM", jenis: "SK" },
    { kod: "MBB0044", nama: "SEKOLAH KEBANGSAAN SRI LAKSAMANA", jenis: "SK" },
    { kod: "MBC0046", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) PAY CHEE", jenis: "SJKC" },
    { kod: "MBC0047", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) ALOR GAJAH", jenis: "SJKC" },
    { kod: "MBC0048", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) SANN YUH", jenis: "SJKC" },
    { kod: "MBC0049", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) PENG MIN", jenis: "SJKC" },
    { kod: "MBC0050", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) SIN WAH", jenis: "SJKC" },
    { kod: "MBC0051", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) KIOW MIN", jenis: "SJKC" },
    { kod: "MBC0052", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) MACHAP BARU", jenis: "SJKC" },
    { kod: "MBC0053", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) MACHAP UMBOO", jenis: "SJKC" },
    { kod: "MBC0054", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) TABOH NANING", jenis: "SJKC" },
    { kod: "MBC0055", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) LENDU", jenis: "SJKC" },
    { kod: "MBC0056", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) KHIAK YEW", jenis: "SJKC" },
    { kod: "MBC0057", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) MASJID TANAH", jenis: "SJKC" },
    { kod: "MBC0058", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) YOK SIN", jenis: "SJKC" },
    { kod: "MBC0059", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) PAYA MENGKUANG", jenis: "SJKC" },
    { kod: "MBC0060", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) SIN MIN", jenis: "SJKC" },
    { kod: "MBC0061", nama: "SEKOLAH JENIS KEBANGSAAN (CINA) CHABAU", jenis: "SJKC" },
    { kod: "MBD0061", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) ALOR GAJAH", jenis: "SJKT" },
    { kod: "MBD0062", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) DURIAN TUNGGAL", jenis: "SJKT" },
    { kod: "MBD0063", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) RUMBIA", jenis: "SJKT" },
    { kod: "MBD0064", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) LADANG GADEK", jenis: "SJKT" },
    { kod: "MBD0066", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) KEMUNING (H/D)", jenis: "SJKT" },
    { kod: "MBD0067", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) LDG KEMUNING KRU DIVISION", jenis: "SJKT" },
    { kod: "MBD0068", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) PULAU SEBANG", jenis: "SJKT" },
    { kod: "MBD0069", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) LDG SG BARU (H/D)", jenis: "SJKT" },
    { kod: "MBD0070", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) LDG TEBONG", jenis: "SJKT" },
    { kod: "MBD0097", nama: "SEKOLAH JENIS KEBANGSAAN (TAMIL) PEKAN TEBONG", jenis: "SJKT" },
    { kod: "MBE0045", nama: "SEKOLAH KEBANGSAAN KEM TERENDAK 1", jenis: "SK" },
    { kod: "MCT0001", nama: "SEKOLAH RENDAH ARAB (JAIM) AL-FALAH", jenis: "SR SABK" },
    { kod: "MCT0002", nama: "SEKOLAH RENDAH ARAB (JAIM) AL-FAIZIN", jenis: "SR SABK" },
    { kod: "MEA0071", nama: "SEKOLAH MENENGAH KEBANGSAAN GHAFAR BABA", jenis: "SMK" },
    { kod: "MEA0072", nama: "SEKOLAH MENENGAH KEBANGSAAN DATO' HAJI TALIB KARIM", jenis: "SMK" },
    { kod: "MEA0073", nama: "SEKOLAH MENENGAH KEBANGSAAN RAHMAT", jenis: "SMK" },
    { kod: "MEA0074", nama: "SEKOLAH MENENGAH KEBANGSAAN ADE PUTRA", jenis: "SMK" },
    { kod: "MEA0075", nama: "SEKOLAH MENENGAH KEBANGSAAN NANING", jenis: "SMK" },
    { kod: "MEA0095", nama: "SEKOLAH MENENGAH KEBANGSAAN LUBOK CHINA", jenis: "SMK" },
    { kod: "MEA0099", nama: "SEKOLAH MENENGAH KEBANGSAAN HANG KASTURI", jenis: "SMK" },
    { kod: "MEA0100", nama: "SEKOLAH MENENGAH KEBANGSAAN SUNGAI UDANG", jenis: "SMK" },
    { kod: "MEA0101", nama: "SEKOLAH MENENGAH KEBANGSAAN DURIAN TUNGGAL", jenis: "SMK" },
    { kod: "MEA0102", nama: "SEKOLAH MENENGAH KEBANGSAAN TEBONG", jenis: "SMK" },
    { kod: "MEA0103", nama: "SEKOLAH MENENGAH SAINS DATUK SETIA ABDUL GHANI ALI", jenis: "SBP" },
    { kod: "MEB0077", nama: "SEKOLAH MENENGAH KEBANGSAAN SERI PENGKALAN", jenis: "SMK" },
    { kod: "MEB0078", nama: "SEKOLAH MENENGAH KEBANGSAAN PULAU SEBANG", jenis: "SMK" },
    { kod: "MEB0079", nama: "SEKOLAH MENENGAH KEBANGSAAN SULTAN ALAUDDIN", jenis: "SMK" },
    { kod: "MEE0074", nama: "SEKOLAH MENENGAH KEBANGSAAN SULTAN MANSOR SHAH", jenis: "SMK" },
    { kod: "MEE0075", nama: "SEKOLAH MENENGAH KEBANGSAAN DATO' DOL SAID", jenis: "SMK" },
    { kod: "MEE0094", nama: "SEKOLAH MENENGAH KEBANGSAAN KEM TERENDAK", jenis: "SMK" },
    { kod: "MFT0001", nama: "SEKOLAH MENENGAH AGAMA AL-EHYA AL-KARIM", jenis: "SM SABK" },
    { kod: "MFT0002", nama: "SEKOLAH MENENGAH AGAMA (JAIM) AL-ASYRAF", jenis: "SM SABK" },
    { kod: "MFT0003", nama: "SEKOLAH MENENGAH AGAMA (JAIM) DARUL FALAH", jenis: "SM SABK" },
    { kod: "MFT0004", nama: "SEKOLAH MENENGAH IMTIAZ ULUL ALBAB MELAKA", jenis: "SM SABK" },
    { kod: "MHA0001", nama: "KOLEJ VOKASIONAL DATUK SERI MOHD. ZIN", jenis: "KV" },
    { kod: "M030", nama: "PEJABAT PENDIDIKAN DAERAH ALOR GAJAH", jenis: "PPD" }
];